us_list = [
"U.S. Space & Rocket Center",
"Birmingham Museum of Art",
"Ono Island",
"Heart of Dixie Railroad Museum",
"Gulf State Park",
"Denali National Park and Preserve",
"Hubbard Glacier",
"Alaska State Museum",
"Eldred Rock Light",
"Chena Hot Springs",
"Grand Canyon National Park",
"Antelope Canyon",
"Havasu Falls",
"Taliesin West",
"Phoenix Zoo",
"Hot Springs National Park",
"Buffalo Rive",
"William J. Clinton Library and Museum",
"Fossil Flats Trailhead",
"Lake Catherine State Park",
"Yosemite National Park",
"Joshua Tree National Park",
"Disneyland",
"San Diego Zoo",
"Alcatraz Island",
"Rocky Mountain National Park",
"Mesa Verde National Park",
"Great Sand Dunes National Park",
"Black Canyon",
"Denver Art Museum",
"Mystic Seaport Museum",
"Mark Twain House and Museum",
"Yale University Art Gallery",
"Mystic Aquarium",
"Wadsworth Atheneum",
"Winterthur Museum, Garden and Library",
"Delaware Art Museum",
"Cape Henlopen State Park",
"Hagley Museum and Library",
"Brandywine Zoo",
"Walt Disney World Resort",
"Universal Orlando Resort",
"Everglades National Park",
"LEGOLAND Florida Resort",
"SeaWorld Orlando",
"Georgia Aquarium",
"High Museum of Art",
"World of Coca-Cola",
"Zoo Atlanta",
"Rock City",
"Hawaiʻi Volcanoes National Park",
"Hana Highway",
"Nā Pali Coast State Park",
"Aulani, a Disney Resort & Spa",
"Haleakalā National Park",
"Craters of the Moon National Monument and Preserve",
"Schweitzer",
"Shoshone Falls",
"Silver Mountain",
"Bogus Basin",
"The Art Institute of Chicago",
"Field Museum",
"Navy Pier",
"Shedd Aquarium",
"Millennium Park",
"Indiana Dunes National Park",
"Childrens Museum of Indianapolis",
"Indianapolis Museum of Art",
"Holiday World & Splashin' Safari",
"Indianapolis Zoo",
"Effigy Mounds National Monument",
"Des Moines Art Center",
"Blank Park Zoo",
"Adventureland Resort",
"Maquoketa Caves State Park",
"Sedgwick County Zoo",
"Tallgrass Prairie National Preserve",
"Wichita Art Museum",
"Exploration Place",
"Spencer Museum of Art",
"Mammoth Cave National Park",
"Louisville Slugger Museum & Factory",
"Red River Gorge",
"Newport Aquarium",
"Louisville Zoo",
"National WWII Museum",
"Jackson Square",
"New Orleans Museum of Art",
"Bourbon Street",
"Café du Monde",
"Acadia National Park",
"Portland Head Light",
"Sunday River",
"Cadillac Mountain",
"Portland Museum of Art",
"National Aquarium",
"Walters Art Museum",
"American Visionary Art Museum",
"Antietam National Battlefield",
"George Peabody Library",
"Museum of Fine Arts",
"Museum of Science",
"New England Aquarium",
"Isabella Stewart Gardner Museum",
"Fenway Park",
"Detroit Institute of Arts",
"Sleeping Bear Dunes National Lakeshore",
"Mackinac Island",
"Pictured Rocks National Lakeshore",
"Henry Ford",
"Voyageurs National Park",
"Minneapolis Institute of Art",
"Walker Art Center",
"Mall of America",
"Boundary Waters Canoe Area Wilderness",
"Gulf Islands National Seashore",
"Elvis Presley Birthplace",
"Vicksburg National Military Park",
"Mississippi Museum of Art",
"Hard Rock Hotel and Casino Biloxi",
"Gateway Arch",
"Nelson-Atkins Museum of Art",
"Silver Dollar City",
"Missouri Botanical Garden",
"City Museum",
"Glacier National Park",
"Big Sky Resort",
"Going-to-the-Sun Road",
"Whitefish Mountain Resort",
"Lake McDonald",
"Omaha's Henry Doorly Zoo and Aquarium",
"Joslyn Art Museum",
"Carhenge",
"Scotts Bluff National Monument",
"Durham Museum",
"Bellagio Resort & Casino",
"Venetian Las Vegas",
"Hoover Dam",
"Red Rock Canyon National Conservation Area",
"Valley of Fire State Park",
"Mount Washington",
"Loon Mountain Resort",
"Attitash Mountain Resort",
"Gunstock Mountain Resort",
"Cranmore Mountain Resort",
"Six Flags Great Adventure",
"Adventure Aquarium",
"Newark Museum of Art",
"Grounds For Sculpture",
"Mountain Creek Resort",
"Carlsbad Caverns National Park",
"White Sands National Park",
"Chaco Culture National Historical Park",
"Bandelier National Monument",
"Petroglyph National Monument",
"Metropolitan Museum of Art",
"Central Park",
"Museum of Modern Art",
"Statue of Liberty",
"Empire State Building",
"Biltmore Estate",
"Clingmans Dome",
"Pisgah National Forest",
"Wright Brothers National Memorial",
"North Carolina Museum of Art",
"Theodore Roosevelt National Park",
"Enchanted Highway",
"Fort Abraham Lincoln State Park",
"Chateau de Mores",
"Plains Art Museum",
"Cuyahoga Valley National Park",
"Cleveland Museum of Art",
"Cedar Point",
"Cincinnati Zoo & Botanical Garden",
"Kings Island Park",
"National Cowboy & Western Heritage Museum",
"Oklahoma City National Memorial",
"Philbrook Museum of Art",
"Oklahoma City Zoo and Botanical Garden",
"Myriad Botanical Gardens",
"Crater Lake National Park",
"Mount Hood",
"Multnomah Falls",
"Timberline Lodge",
"Portland Art Museum",
"Philadelphia Museum of Art",
"Fallingwater",
"Longwood Gardens",
"Independence Hall",
"Liberty Bell",
"Rhode Island School of Design",
"The Breakers",
"Roger Williams Park Zoo",
"Rosecliff",
"Marble House",
"Congaree National Park",
"Brookgreen Gardens",
"Fort Sumter National Monument",
"Magnolia Plantation and Gardens",
"Broadway at the Beach",
]
us_url = []
for link in us_list:
    link = link.replace(" ","_")
    # print(link)
    url = "https://en.wikipedia.org/wiki/"+link
    us_url.append(url)

for url in us_url:
    print(url)

us_list = [
"https://en.wikipedia.org/wiki/U.S._Space_&_Rocket_Center",
"https://en.wikipedia.org/wiki/Birmingham_Museum_of_Art",
"https://en.wikipedia.org/wiki/Ono_Island",
"https://en.wikipedia.org/wiki/Heart_of_Dixie_Railroad_Museum",
"https://en.wikipedia.org/wiki/Gulf_State_Park",
"https://en.wikipedia.org/wiki/Denali_National_Park_and_Preserve",
"https://en.wikipedia.org/wiki/Hubbard_Glacier",
"https://en.wikipedia.org/wiki/Alaska_State_Museum",
"https://en.wikipedia.org/wiki/Eldred_Rock_Light",
"https://en.wikipedia.org/wiki/Chena_Hot_Springs",
"https://en.wikipedia.org/wiki/Grand_Canyon_National_Park",
"https://en.wikipedia.org/wiki/Antelope_Canyon",
"https://en.wikipedia.org/wiki/Havasu_Falls",
"https://en.wikipedia.org/wiki/Taliesin_West",
"https://en.wikipedia.org/wiki/Phoenix_Zoo",
"https://en.wikipedia.org/wiki/Hot_Springs_National_Park",
"https://en.wikipedia.org/wiki/Buffalo_Rive",
"https://en.wikipedia.org/wiki/William_J._Clinton_Library_and_Museum",
"https://en.wikipedia.org/wiki/Fossil_Flats_Trailhead",
"https://en.wikipedia.org/wiki/Lake_Catherine_State_Park",
"https://en.wikipedia.org/wiki/Yosemite_National_Park",
"https://en.wikipedia.org/wiki/Joshua_Tree_National_Park",
"https://en.wikipedia.org/wiki/Disneyland",
"https://en.wikipedia.org/wiki/San_Diego_Zoo",
"https://en.wikipedia.org/wiki/Alcatraz_Island",
"https://en.wikipedia.org/wiki/Rocky_Mountain_National_Park",
"https://en.wikipedia.org/wiki/Mesa_Verde_National_Park",
"https://en.wikipedia.org/wiki/Great_Sand_Dunes_National_Park",
"https://en.wikipedia.org/wiki/Black_Canyon",
"https://en.wikipedia.org/wiki/Denver_Art_Museum",
"https://en.wikipedia.org/wiki/Mystic_Seaport_Museum",
"https://en.wikipedia.org/wiki/Mark_Twain_House_and_Museum",
"https://en.wikipedia.org/wiki/Yale_University_Art_Gallery",
"https://en.wikipedia.org/wiki/Mystic_Aquarium",
"https://en.wikipedia.org/wiki/Wadsworth_Atheneum",
"https://en.wikipedia.org/wiki/Winterthur_Museum,_Garden_and_Library",
"https://en.wikipedia.org/wiki/Delaware_Art_Museum",
"https://en.wikipedia.org/wiki/Cape_Henlopen_State_Park",
"https://en.wikipedia.org/wiki/Hagley_Museum_and_Library",
"https://en.wikipedia.org/wiki/Brandywine_Zoo",
"https://en.wikipedia.org/wiki/Walt_Disney_World_Resort",
"https://en.wikipedia.org/wiki/Universal_Orlando_Resort",
"https://en.wikipedia.org/wiki/Everglades_National_Park",
"https://en.wikipedia.org/wiki/LEGOLAND_Florida_Resort",
"https://en.wikipedia.org/wiki/SeaWorld_Orlando",
"https://en.wikipedia.org/wiki/Georgia_Aquarium",
"https://en.wikipedia.org/wiki/High_Museum_of_Art",
"https://en.wikipedia.org/wiki/World_of_Coca-Cola",
"https://en.wikipedia.org/wiki/Zoo_Atlanta",
"https://en.wikipedia.org/wiki/Rock_City",
"https://en.wikipedia.org/wiki/Hawai%CA%BBi_Volcanoes_National_Park",
"https://en.wikipedia.org/wiki/Hana_Highway",
"https://en.wikipedia.org/wiki/N%C4%81_Pali_Coast_State_Park",
"https://en.wikipedia.org/wiki/Aulani,_a_Disney_Resort_&_Spa",
"https://en.wikipedia.org/wiki/Haleakal%C4%81_National_Park",
"https://en.wikipedia.org/wiki/Craters_of_the_Moon_National_Monument_and_Preserve",
"https://en.wikipedia.org/wiki/Schweitzer",
"https://en.wikipedia.org/wiki/Shoshone_Falls",
"https://en.wikipedia.org/wiki/Silver_Mountain",
"https://en.wikipedia.org/wiki/Bogus_Basin",
"https://en.wikipedia.org/wiki/The_Art_Institute_of_Chicago",
"https://en.wikipedia.org/wiki/Field_Museum",
"https://en.wikipedia.org/wiki/Navy_Pier",
"https://en.wikipedia.org/wiki/Shedd_Aquarium",
"https://en.wikipedia.org/wiki/Millennium_Park",
"https://en.wikipedia.org/wiki/Indiana_Dunes_National_Park",
"https://en.wikipedia.org/wiki/Childrens_Museum_of_Indianapolis",
"https://en.wikipedia.org/wiki/Indianapolis_Museum_of_Art",
"https://en.wikipedia.org/wiki/Holiday_World_&_Splashin'_Safari",
"https://en.wikipedia.org/wiki/Indianapolis_Zoo",
"https://en.wikipedia.org/wiki/Effigy_Mounds_National_Monument",
"https://en.wikipedia.org/wiki/Des_Moines_Art_Center",
"https://en.wikipedia.org/wiki/Blank_Park_Zoo",
"https://en.wikipedia.org/wiki/Adventureland_Resort",
"https://en.wikipedia.org/wiki/Maquoketa_Caves_State_Park",
"https://en.wikipedia.org/wiki/Sedgwick_County_Zoo",
"https://en.wikipedia.org/wiki/Tallgrass_Prairie_National_Preserve",
"https://en.wikipedia.org/wiki/Wichita_Art_Museum",
"https://en.wikipedia.org/wiki/Exploration_Place",
"https://en.wikipedia.org/wiki/Spencer_Museum_of_Art",
"https://en.wikipedia.org/wiki/Mammoth_Cave_National_Park",
"https://en.wikipedia.org/wiki/Louisville_Slugger_Museum_&_Factory",
"https://en.wikipedia.org/wiki/Red_River_Gorge",
"https://en.wikipedia.org/wiki/Newport_Aquarium",
"https://en.wikipedia.org/wiki/Louisville_Zoo",
"https://en.wikipedia.org/wiki/National_WWII_Museum",
"https://en.wikipedia.org/wiki/Jackson_Square",
"https://en.wikipedia.org/wiki/New_Orleans_Museum_of_Art",
"https://en.wikipedia.org/wiki/Bourbon_Street",
"https://en.wikipedia.org/wiki/Caf%C3%A9_du_Monde",
"https://en.wikipedia.org/wiki/Acadia_National_Park",
"https://en.wikipedia.org/wiki/Portland_Head_Light",
"https://en.wikipedia.org/wiki/Sunday_River",
"https://en.wikipedia.org/wiki/Cadillac_Mountain",
"https://en.wikipedia.org/wiki/Portland_Museum_of_Art",
"https://en.wikipedia.org/wiki/National_Aquarium",
"https://en.wikipedia.org/wiki/Walters_Art_Museum",
"https://en.wikipedia.org/wiki/American_Visionary_Art_Museum",
"https://en.wikipedia.org/wiki/Antietam_National_Battlefield",
"https://en.wikipedia.org/wiki/George_Peabody_Library",
"https://en.wikipedia.org/wiki/Museum_of_Fine_Arts",
"https://en.wikipedia.org/wiki/Museum_of_Science",
"https://en.wikipedia.org/wiki/New_England_Aquarium",
"https://en.wikipedia.org/wiki/Isabella_Stewart_Gardner_Museum",
"https://en.wikipedia.org/wiki/Fenway_Park",
"https://en.wikipedia.org/wiki/Detroit_Institute_of_Arts",
"https://en.wikipedia.org/wiki/Sleeping_Bear_Dunes_National_Lakeshore",
"https://en.wikipedia.org/wiki/Mackinac_Island",
"https://en.wikipedia.org/wiki/Pictured_Rocks_National_Lakeshore",
"https://en.wikipedia.org/wiki/Henry_Ford",
"https://en.wikipedia.org/wiki/Voyageurs_National_Park",
"https://en.wikipedia.org/wiki/Minneapolis_Institute_of_Art",
"https://en.wikipedia.org/wiki/Walker_Art_Center",
"https://en.wikipedia.org/wiki/Mall_of_America",
"https://en.wikipedia.org/wiki/Boundary_Waters_Canoe_Area_Wilderness",
"https://en.wikipedia.org/wiki/Gulf_Islands_National_Seashore",
"https://en.wikipedia.org/wiki/Elvis_Presley_Birthplace",
"https://en.wikipedia.org/wiki/Vicksburg_National_Military_Park",
"https://en.wikipedia.org/wiki/Mississippi_Museum_of_Art",
"https://en.wikipedia.org/wiki/Hard_Rock_Hotel_and_Casino_Biloxi",
"https://en.wikipedia.org/wiki/Gateway_Arch",
"https://en.wikipedia.org/wiki/Nelson-Atkins_Museum_of_Art",
"https://en.wikipedia.org/wiki/Silver_Dollar_City",
"https://en.wikipedia.org/wiki/Missouri_Botanical_Garden",
"https://en.wikipedia.org/wiki/City_Museum",
"https://en.wikipedia.org/wiki/Glacier_National_Park",
"https://en.wikipedia.org/wiki/Big_Sky_Resort",
"https://en.wikipedia.org/wiki/Going-to-the-Sun_Road",
"https://en.wikipedia.org/wiki/Whitefish_Mountain_Resort",
"https://en.wikipedia.org/wiki/Lake_McDonald",
"https://en.wikipedia.org/wiki/Omaha's_Henry_Doorly_Zoo_and_Aquarium",
"https://en.wikipedia.org/wiki/Joslyn_Art_Museum",
"https://en.wikipedia.org/wiki/Carhenge",
"https://en.wikipedia.org/wiki/Scotts_Bluff_National_Monument",
"https://en.wikipedia.org/wiki/Durham_Museum",
"https://en.wikipedia.org/wiki/Bellagio_Resort_&_Casino",
"https://en.wikipedia.org/wiki/Venetian_Las_Vegas",
"https://en.wikipedia.org/wiki/Hoover_Dam",
"https://en.wikipedia.org/wiki/Red_Rock_Canyon_National_Conservation_Area",
"https://en.wikipedia.org/wiki/Valley_of_Fire_State_Park",
"https://en.wikipedia.org/wiki/Mount_Washington",
"https://en.wikipedia.org/wiki/Loon_Mountain_Resort",
"https://en.wikipedia.org/wiki/Attitash_Mountain_Resort",
"https://en.wikipedia.org/wiki/Gunstock_Mountain_Resort",
"https://en.wikipedia.org/wiki/Cranmore_Mountain_Resort",
"https://en.wikipedia.org/wiki/Six_Flags_Great_Adventure",
"https://en.wikipedia.org/wiki/Adventure_Aquarium",
"https://en.wikipedia.org/wiki/Newark_Museum_of_Art",
"https://en.wikipedia.org/wiki/Grounds_For_Sculpture",
"https://en.wikipedia.org/wiki/Mountain_Creek_Resort",
"https://en.wikipedia.org/wiki/Carlsbad_Caverns_National_Park",
"https://en.wikipedia.org/wiki/White_Sands_National_Park",
"https://en.wikipedia.org/wiki/Chaco_Culture_National_Historical_Park",
"https://en.wikipedia.org/wiki/Bandelier_National_Monument",
"https://en.wikipedia.org/wiki/Petroglyph_National_Monument",
"https://en.wikipedia.org/wiki/Metropolitan_Museum_of_Art",
"https://en.wikipedia.org/wiki/Central_Park",
"https://en.wikipedia.org/wiki/Museum_of_Modern_Art",
"https://en.wikipedia.org/wiki/Statue_of_Liberty",
"https://en.wikipedia.org/wiki/Empire_State_Building",
"https://en.wikipedia.org/wiki/Biltmore_Estate",
"https://en.wikipedia.org/wiki/Clingmans_Dome",
"https://en.wikipedia.org/wiki/Pisgah_National_Forest",
"https://en.wikipedia.org/wiki/Wright_Brothers_National_Memorial",
"https://en.wikipedia.org/wiki/North_Carolina_Museum_of_Art",
"https://en.wikipedia.org/wiki/Theodore_Roosevelt_National_Park",
"https://en.wikipedia.org/wiki/Enchanted_Highway",
"https://en.wikipedia.org/wiki/Fort_Abraham_Lincoln_State_Park",
"https://en.wikipedia.org/wiki/Chateau_de_Mores",
"https://en.wikipedia.org/wiki/Plains_Art_Museum",
"https://en.wikipedia.org/wiki/Cuyahoga_Valley_National_Park",
"https://en.wikipedia.org/wiki/Cleveland_Museum_of_Art",
"https://en.wikipedia.org/wiki/Cedar_Point",
"https://en.wikipedia.org/wiki/Cincinnati_Zoo_&_Botanical_Garden",
"https://en.wikipedia.org/wiki/Kings_Island_Park",
"https://en.wikipedia.org/wiki/National_Cowboy_&_Western_Heritage_Museum",
"https://en.wikipedia.org/wiki/Oklahoma_City_National_Memorial",
"https://en.wikipedia.org/wiki/Philbrook_Museum_of_Art",
"https://en.wikipedia.org/wiki/Oklahoma_City_Zoo_and_Botanical_Garden",
"https://en.wikipedia.org/wiki/Myriad_Botanical_Gardens",
"https://en.wikipedia.org/wiki/Crater_Lake_National_Park",
"https://en.wikipedia.org/wiki/Mount_Hood",
"https://en.wikipedia.org/wiki/Multnomah_Falls",
"https://en.wikipedia.org/wiki/Timberline_Lodge",
"https://en.wikipedia.org/wiki/Portland_Art_Museum",
"https://en.wikipedia.org/wiki/Philadelphia_Museum_of_Art",
"https://en.wikipedia.org/wiki/Fallingwater",
"https://en.wikipedia.org/wiki/Longwood_Gardens",
"https://en.wikipedia.org/wiki/Independence_Hall",
"https://en.wikipedia.org/wiki/Liberty_Bell",
"https://en.wikipedia.org/wiki/Rhode_Island_School_of_Design",
"https://en.wikipedia.org/wiki/The_Breakers",
"https://en.wikipedia.org/wiki/Roger_Williams_Park_Zoo",
"https://en.wikipedia.org/wiki/Rosecliff",
"https://en.wikipedia.org/wiki/Marble_House",
"https://en.wikipedia.org/wiki/Congaree_National_Park",
"https://en.wikipedia.org/wiki/Brookgreen_Gardens",
"https://en.wikipedia.org/wiki/Fort_Sumter_National_Monument",
"https://en.wikipedia.org/wiki/Magnolia_Plantation_and_Gardens",
"https://en.wikipedia.org/wiki/Broadway_at_the_Beach"
]    